workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.hearmysign.app
    scripts:
      - name: Disable Swift Package Manager
        script: flutter config --no-enable-swift-package-manager
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
